version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bun-rest-api
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/bun-rest-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: [ "sh", "-c", "bunx prisma migrate dev && bun run dev" ]

volumes:
  mysql_data:
